# Generated by Django 5.1.1 on 2024-10-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(default=12345678, on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to='banking.customer'),
        ),
    ]
