# Generated by Django 5.1.1 on 2024-10-22 19:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_installments_installment_id_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_account', 'Can View Account'), ('view_transactions', 'Can View Transactions'), ('view_loan', 'Can View Loan'), ('view_installments', 'Can View Installments'), ('view_atm_cards', 'Can View ATM Cards'), ('view_customer', 'Can View Customer Info'), ('add_transactions', 'Can Create Transactions'), ('add_installments', 'Can Create Loan Installments'), ('edit_atm_monthly_limit', 'Can Edit Monthly Limit for ATM Card'), ('edit_mpin_mtpin', 'Can Edit MPIN and MTPIN'), ('edit_password', 'Can Change Password'), ('edit_account', 'Can Alter Account'), ('edit_loan', 'Can Alter Loan')]},
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.BigIntegerField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='atm_cards',
            name='card_no',
            field=models.BigIntegerField(default=1111222233334444, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(1000000000000000)]),
        ),
        migrations.AlterField(
            model_name='atm_cards',
            name='cvv',
            field=models.IntegerField(default=111, editable=False, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cin',
            field=models.BigIntegerField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.BigIntegerField(default=100000, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='installments',
            name='installment_amt',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installments',
            name='installment_id',
            field=models.BigIntegerField(blank=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.BigIntegerField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_issue_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_amt',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10, verbose_name='Transaction Amount'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.BigIntegerField(blank=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID'),
        ),
    ]
