# Generated by Django 5.1.1 on 2024-10-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_transactions_from_acc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('edit_atm_monthly_limit', 'Can Edit Monthly Limit for ATM Card'), ('edit_mpin_mtpin', 'Can Edit MPIN and MTPIN'), ('edit_password', 'Can Change Password'), ('edit_account', 'Can Alter Account'), ('edit_loan', 'Can Alter Loan')]},
        ),
    ]
