# Generated by Django 5.1.1 on 2024-10-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_supportrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='acc_in_charge',
        ),
        migrations.AddField(
            model_name='customer',
            name='managed_by',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_in_charge', to='banking.employee'),
        ),
    ]
