# Generated by Django 5.1.1 on 2024-10-24 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_remove_employee_acc_in_charge_customer_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_amt',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_inst_date',
            field=models.DateField(blank=True),
        ),
    ]
